/*
-- Query: SELECT * FROM shopping1.admin

-- to insert two admins in table 

*/
INSERT INTO shopping1.admin (`email`,`passwrd`) VALUES ('admin1@gmail.com','admin');
INSERT INTO shopping1.admin (`email`,`passwrd`) VALUES ('admin2@gmail.com','admin');


/*
-- Query: SELECT * FROM shopping1.category
LIMIT 0, 1000

-- insert four categories 
*/
INSERT INTO `` (`image`,`name`,`description`) VALUES ('https://i0.wp.com/southeastagnet.com/wp-content/uploads/2016/08/raw-meat-2.jpg','MEAT & POULTRY','MEAT & POULTRY');
INSERT INTO `` (`image`,`name`,`description`) VALUES ('https://cdn.shopify.com/s/files/1/0562/5928/1092/files/DAIRY_EGG_1000x562.jpg?v=1632148012','CHEESE, DAIRY & EGGS','CHEESE, DAIRY & EGGS');
INSERT INTO `` (`image`,`name`,`description`) VALUES ('https://media.istockphoto.com/photos/beautiful-flat-lay-composition-with-different-kinds-of-mixed-fresh-picture-id934043388','FRESH FRUITS, VEGETABLES & HERBS','FRESH FRUITS, VEGETABLES & HERBS');
INSERT INTO `` (`image`,`name`,`description`) VALUES ('https://lh3.googleusercontent.com/proxy/L6okCdq-kIzTtBs5SxJNjcNIO1hQ6RgUnzGz8t8qa96yWmjOC5ko0j8okaahfrIcBgOaNsf1C-q9M-M0fFUdfZ8hY6xzYeCqfjkFkklLTTWUVnzcx1d5TbE','FISH & SEAFOOD','FISH & SEAFOOD');

/*
-- Query: SELECT * FROM shopping1.product
LIMIT 0, 1000

-- insert statement in product table 
*/
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/2/0/2011054000000_aussie-beef-carpaccio.jpg','Chilled Aussie Beef Carpaccio',80,7,'The culinary delicacy is made of premium quality Australian beef. It is cut in paper thin beef slices and meant to be served raw. Drizzle with extra virgin olive oil and a little balsamic vinegar, sprinkle with Maldon sea salt and freshly ground black pepper, top with a few rocket leaves and add sprinkle Parmesan shavings on top. A delicious and simple appetizer prepared in few minutes. About our Beef: The Australian beef industry produces some of the finest beef in the world. The industry is geared to producing high quality grass-fed, grain-fed and organic beef and breed-specific products, such as Wagu and Angus. Australian beef has the natural-advantage, where the cattle graze on open pasture and most are exclusively grass-fed. Our top-quality meat is assessed for its rib fat, meat colour, eye muscle area, fat colour and marbling. All our beef is 100% halal.',1,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/2/0/2011010000000_aussie-beef-sirloinsteak.jpg','Chilled Aussie Beef Sirloin Steak',325,5,'If you are craving steak for dinner, our fresh sirloin steak is an excellent choice. It is perfect for any occasion! It\'s juicy and tender with a strong beef flavour that meat lovers just adore. Simply season with Maldon sea salt and pepper and cook to medium to achieve the best results. We recommend serving it with potatoes and roasted vegetables to complete your delicious dinner. About our Beef: The Australian beef industry produces some of the finest beef in the world. The industry is geared to producing high quality grass-fed, grain-fed and organic beef and breed-specific products, such as Wagu and Angus. Australian beef has the natural-advantage, where the cattle graze on open pasture and most are exclusively grass-fed. Our top-quality meat is assessed for its rib fat, meat colour, eye muscle area, fat colour and marbling. All our beef is 100% halal.',1,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/2/0/2011084000000_aussie-beef-dawood-pasha.jpg','Chilled Aussie Beef Dawood Pasha Meat Balls',120,8,'Spiced, rolled and ready to cook classic Dawood Pasha meat balls! Prepare these oriental favorites in the traditional way or reinvent the recipe. They are a guaranteed hit! About our Beef: The Australian beef industry produces some of the finest beef in the world. The industry is geared to producing high quality grass-fed, grain-fed and organic beef and breed-specific products, such as Wagu and Angus. Our top-quality meat is assessed for its rib fat, meat colour, eye muscle area, fat colour and marbling. All our beef is 100% halal.',1,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://static.onecms.io/wp-content/uploads/sites/9/2013/12/06/200906-r-xl-middle-eastern-lamb-skewers.jpg','Arabic Lamb Fillet Kebab',375,10,'Tender fillet seasoned with Arabic spices offering a burst of beautiful flavours. Can be seared, grilled or barbecued.\n',1,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://www.cubesnjuliennes.com/wp-content/uploads/2019/11/Tandoori-Chicken-1.jpg','Tandoori Chicken DrumStick',45,3,'Ingredients\nCoriander, Cumin, Turmeric, Hot Chili Powder, Lemon, Garlic, Curry Powder, Yogurt, Salt, Black Pepper, Ginger, Nutmeg, Clove, Cinnamon\n',1,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/g/o/gourmet-greek-style-yogurt-with-granola_-honey-_-berries_1_1.jpg','Gourmet Greek Yogurt with Honey, Muesli & Berries',60,10,'Enjoy our smooth and creamy Greek Yogurt with a drizzle of rich honey, and our crunchy & nutty granola and berries. This protein packed product is the perfect choice for a wholesome breakfast, pre-workout fuelling meal or midday snack.\nDoes not contain any artificial thickeners.',2,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/3/2/3254550025090.jpg','Isigny Ste-Mère Salted Butter',80,12,'The Isigny Ste Mere Beurre D\'Isigny Salted Butter has the perfect blend of creamy, salty, and savory. This salted butter can be used to baste pan-seared steak or grill sandwiches to take your lunch or dinner up a notch.\nIngredients\nCream from Pasteurised Milk, Ferments, Salt 2%.',2,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/e/g/egg3.jpg','Al Alamya White Eggs',35,9,'Fresh and premium white eggs straight from the farm. They are loaded with nutrients and high in quality protein with all the essential amino acids. Enjoy them scrambled, poached or boiled with sliced avocado and Gourmet\'s Norwegian smoked salmon for a nutritious, delicious and filing breakfast. Master making homemade omelette and add filling of your choice, Gourmet Italian shredded mozzarella, mushrooms, chives and mushrooms and serve with our freshly-baked breads! The pack contains 10 farm fresh eggs.',2,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/8/8/8851409000588.jpg','Rizi World Coconut Milk',30,6,'Perfectly creamy coconut milk. Use as an ingredient for Thai curries, stir-fries, desserts & marinades.',2,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/2b4d21b90ad5abb98380bc0a709a4ac8/c/r/cranberry_cheese.png','Somerdale Wensleydale & Cranberries Cheese',80,10,'Wensleydale is the perfect cheese to eat with fruit. Creamy with an open texture, Wensleydale is one of the oldest cheese varieties in England. Wensleydale has a natural sweet acidity that complements fruit, best of all cranberries. Plump cranberries are added to the cheese creating a great, sweet and juicy cheese. Somerdale Wensleydale & Cranberries is free of artificial sweeteners and made with only natural ingredients. This cheese makes for a wonderful dessert cheese when served on sweetened or ginger crackers and is also great crumbled over a salad.\n\nIngredients\nWensleydale Cheese (Pasteurized Cows Milk, Salt, Starter Culture, Vegetarian Rennet), Sweetened Dried Cranberries (Cranberries, Sugar, Sunflower Oil)',2,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/b8cd361684aa05088effd025b326e607/s/w/sweet_potatoess.jpg','Organic Sweet Potato, Sara',32,5,'Delicious and flavorful sweet potatoes are healthy and nutritious. They are a good source of fiber and are rich in vitamins A and C and manganese. Sweet potatoes are extremely versatile and can be eaten sweet or savory. Try them baked, mashed, fried or enjoy them for dessert by making a sweet potato casserole.\nIngredients\nSweet Potato',3,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/6/0/6025175000000_123_.jpg','Gourmet Fruit Skewers Platter',325,10,'Share the fruity entertainment with Gourmet’s Fruit Skewer platter. A luscious medley of fresh seasonal fruits; this rainbow of sweetness is your ticket to a guiltless, juicy, happy get-together!\n\nHow to order your party platter?\nAllow 4 hours for preparation & delivery.\nAll platters can be ordered in either round or rectangular glass bases, as per your preference.\nDepending on availability some ingredients on this platter may be substituted with similar and equally good products.\n\nPreparation & Serving:\nAll platters are served on high-quality glass bases.\nAll platters should be refrigerated until served.\nBest consumed within 2 days.\nAll our party platters will look like the featured images.\n\nIngredients\nSeasonal Fruits',3,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn-reichelt.de/bilder/web/xxl_ws/X200/VERITABLE_VLIN-F5-COU015_01.png','Organic Zucchini Flowers, Ramsco',32,3,'Organic zucchini flower perfect for the famous Italian Stuffed Flower Zucchini dish!',3,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/6/2/6224001091032.jpg','Organic Golden Onions, Jana',22,4,'Use in stews, classic French onion soup, in sauces, on burgers and pizzas, in stir fries and much more. Jana is an organic company based on exporting fresh fruits and vegetables all around the world since 2003. It has gained great trust in the European market in countries such as Denmark, Germany, France , Belgium, Sweden, Netherlands, also it has been exporting to Russia, Canada and alot of arab countries. Jana grows it\'s own products in it\'s farms and packs in it\'s pack houses which undergoes continuous inspection and auditing from various European organization to ensure and sustain the organic and unique quality of it\'s products.',3,NULL);
INSERT INTO `` (`image`,`name`,`price`,`quantity`,`description`,`category_id`,`product_id`) VALUES ('https://cdn.gourmetegypt.com/media/catalog/product/cache/2b4d21b90ad5abb98380bc0a709a4ac8/6/2/6225000113176_2.jpg','Portobello Mushrooms, El Tarouty',33,6,'Portobello mushrooms have a full bodied mushroom flavor. The portobello\'s solid, satisfying earthy taste and texture make it the vegetable version of steak. Serve grilled with balsamic vinegar, crushed garlic and plenty of freshly chopped parsley.',3,NULL);


